version = "1.1.13"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
client = "{icon}{delim}"
client_active = "<span color='red'>{icon}</span>"
# workspace = "<b><span color='red'>{id}-{name}:</span></b>{delim}{clients}"
workspace = "<b><span color='#cba6f7'>{id}:</span></b>{delim}{clients}"
workspace_empty = "<b><span color='yellow'>{id}-{name}:</span></b>{delim}{clients}"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon}]{delim}"

[class_active]
DEFAULT="{icon}"
"(?i)firefox" = "<span color='orange'> {class}</span>"

# [initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

# regex captures support is supported
[title_in_class."(?i)foot"]
"emerge: (.+?/.+?)-.*" = "{match1}"

[initial_title_in_class."kitty"]
"zsh" = "Zsh"

[title_in_class."(brave-browser|firefox|chrom.*)"]
"(?i)youtube" = "<span color='#f38ba8'>ꟳ </span>"
"(?i)twitch" = "ꟳ"
"(?i)Hugging Face" = "<span color='#f9e2af'>:D </span>"
"(?i)HuggingChat" = "<span color='#f9e2af'>:D </span>"

[title_active."(brave-browser|firefox|chrom.*)"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

[title_in_class.""]
"(?i)Spotify" = "<span color='#a6e3a1'> </span>"

[initial_title_in_class.""]
"(?i)Spotify" = "<span color='#a6e3a1'> </span>"

# [title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title."(?i)kitty"]
# "zsh" = "Zsh"

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"

[class]
# DEFAULT = ""
DEFAULT = ""
"(?i)betterbird" = "<span color='#fab387'> </span>"
"(?i)tm" = "<span color='#74c7ec'> </span>"
"@joplin/app-desktop" = "<span color='#89b4fa'>[J]</span>"
"(?i)atril" = "<span color='#f38ba8'> </span>"
"(?i)firefox" = "<span color='orange'> </span>"
"(?i)brave-browser" = "<span color='#f38ba8'> </span>"
"(?i)kitty" = "<span color='#a6e3a1'> </span>"
"(?i)kate" = "<span color='#a6e3a1'> </span>"
"(?i)ImageRoll" = "<span color='#94e2d5'> </span>"
"(?i)codium" = "<span color='#89b4fa'> </span>"
"(?i)pycharm" = "<span color='#a6e3a1'> </span>"
"(?i)ArmCord" = "<span color='#74c7ec'> </span>"
"(?i)chrome-web.whatsapp.com__-Default" = "<span color='green'> </span>"
"thunar" = "<span color='#f9e2af'></span>"
"org.kde.haruna" = "<span color='#b4befe'> </span>"
rclone-browser = "<span color='#89dceb'> </span>"
taskwarrior-tui = ""
xfce4-taskmanager = "<span color='#f38ba8'> </span>"
"(?i)apostrophe-wrapped" = "<span color='#f9e2af'> </span>"

#"(?i)kitty" = ""
#"(?i)alacritty" = ""
bleachbit = ""
burp-startburp = ""
calibre-gui = ""
"chrome-faolnafnngnfdaknnbpnkhgohbobgegn-default" = ""
chromium = ""
"Gimp-2.10" = ""
code-oss = ""
cssh = ""
darktable = ""
dmenu-clipboard = ""
dmenu-pass = ""
duolingo = ""
element = ""
fontforge = ""
gcr-prompter = ""
gsimplecalc = ""
"jetbrains-studio" = ""
"kak" = ""
kicad = ""
"(?i)waydroid.*" = "droid"
obsidian = ""
"dmenu-emoji" = ""
"dmenu-browser" = ""
"dmenu-pass generator" = ""
"qalculate-gtk" = ""
krita = ""
libreoffice-calc = ""
libreoffice-impress = ""
libreoffice-startcenter = ""
libreoffice-writer = ""
molotov = ""
mpv = ""
nm-connection-editor = ""
org-ksnip-ksnip = ""
org-pwmt-zathura = ""
org-qutebrowser-qutebrowser = ""
org-telegram-desktop = ""
paperwork = ""
pavucontrol = ""
personal = ""
plexamp = ""
qutepreview = ""
rapid-photo-downloader = ""
remote-viewer = ""
sandboxed-tor-browser = ""
scli = ""
shopping = ""
Signal = ""
slack = ""
snappergui = ""
songrec = ""
spotify = ""
steam = ""
streamlink-twitch-gui = ""
sun-awt-x11-xframepeer = ""
swappy = ""
telegramdesktop = ""
".*transmission.*" = ""
udiskie = ""
vimiv = ""
virt-manager = ""
vlc = ""
vncviewer = ""
wayvnc = "󰀄"
whatsapp-desktop = ""
whatsapp-nativefier-d52542 = ""
wire = "󰁀"
wireshark-gtk = ""
wlfreerdp = "󰀄"
work = ""
xplr = ""
nemo = ""
zoom = ""

[exclude]
"" = "^$" # prevent displaying clients with empty class
